name: Test & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Check linting
        run: deno lint

      - name: Type check
        run: deno check src/mod.ts

      - name: Run tests
        run: deno task test

      - name: Verify package
        run: deno publish --dry-run

      - name: Generate coverage
        run: deno test -A --coverage=coverage

      - name: Generate LCOV report
        run: deno coverage coverage --lcov > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.lcov
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
